# The Gradle daemon heap size.
# The default is 512m, which is often too small for Android projects using Compose.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Use AndroidX for all libraries.
android.useAndroidX=true

# Enable parallel dexing to speed up builds (requires more memory).
android.enableDexingArtifactTransform.parallel=true
